apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  labels:
    app: res-mgmt-api
  name: res-mgmt-api-ingress
spec:
  rules:
    - host: res-mgmt.92ebbadb-2295-4ddd-9bf8-f9d00f233d62.k8s.civo.com
      http:
        paths:
          -
            backend:
              service:
                name: res-mgmt-api-deployment
                port:
                  number: 8080
            path: /
            pathType: "Prefix"