apiVersion: apps/v1
kind: Deployment
metadata:
  name: res-mgmt-api-deployment
  namespace: clh
  labels:
    app: res-mgmt-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: res-mgmt-api
  template:
    metadata:
      labels:
        app: res-mgmt-api
    spec:
      containers:
      - name: res-mgmt-api
        image: afzal442/resmgmnt-api:v1
        ports:
        - containerPort: 8080

